### ISSUE TITLE
Roadmap for TransferOperators rework

### ISSUE THREAD

**Issue by JordiManyer** [gridap/GridapSolvers.jl#57]
We should rework and standardize the TranferOperator objects in the package. However, I think there is quite a lot to do before we can tackle that, in order to be efficient: 

- [ ] Move GridapDistributed to PA 0.4. This is necessary in order to get the `repartition!` functionality. 
- [ ] Figure out dof gid reordering in distributed FESpaces so that redistributed spaces have matching gids. This is needed for the `repartition!` function to work. We can do this by using the redistribution glue for the redistributed models. 
- [ ] Once we have this, we can use the built-in PA functionality to re-partition the free-values directly for matrix-wise arrays (which should be more efficient than redistributed cell-wise arrays). On top of this, we will end up with cleaner code than can be made modular and re-used. 
- [ ] Finally, I want to create a modular API for transfer operators, so that 
  - [ ] redistribution and fine/coarse transfers are independent
  - [ ] we can work with distributed AND serial arrays
  - [ ] functionalities can be reused between operators (like the redistribution code)
  - [ ] work both on arrays and FEFunctions
